name: Conventional Commits

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Check commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vvoloshchuk777/check-conventional-commits@v1.0.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}