name: Conventional Commits

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taskmedia/action-conventional-commits@v1.1.4
        with:
          types: "feat|fix|build|chore|ci|docs|style|refactor|perf|test"