name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Async
      run: cargo build --verbose --features "async" --no-default-features
    - name: Build Blocking
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  lint: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nightly
      run: rustup toolchain install nightly-2023-10-02-x86_64-unknown-linux-gnu
    - name: Install Clippy
      run: rustup component add clippy --toolchain nightly-2023-10-02-x86_64-unknown-linux-gnu
    - name: clippy check
      run: cargo clippy

  formatting: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nightly
      run: rustup toolchain install nightly-2023-10-02-x86_64-unknown-linux-gnu
    - name: Install rustfmt
      run: rustup component add rustfmt --toolchain nightly-2023-10-02-x86_64-unknown-linux-gnu
    - name: Check Formatting
      run: cargo fmt --all -- --check


